#!/bin/sh

# Return the appropriate architecture string
DetectARCH()
{
	status=1
	case `uname -m` in
		i?86)  echo "x86"
			status=0;;
		*) 
		  case `uname -s` in
		  IRIX*)
			echo "sgi"
			status=0;;
		  *)    
			echo "`uname -m`"
			status=0;;
		  esac
	esac
	return $status
}

# Detect the Linux environment
DetectARCH
